#!/bin/bash

echo "-----Beginning Install------" 
echo "This program will install/check prereqs."

if [[ "$(whoami)" == "root" ]]; then
	echo "FaTaL will not work with root!!"
	exit 1
fi

echo "Will now instal gcalcli"
sudo apt-get install gcalcli

echo "READ CAREFULLY!"
echo "A text editor will now open change the first 3 variables to correspond with your settings!"
read -n1 -r -p "Press any key to continue..." key

nano manager.sh

echo "Installing crontab!"
crontab -l > currentCron

echo "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games" >> currentCron
echo "00 6 * * *  /home/pi/scheduleManager/manager.sh > /home/pi/scheduleManager/tmp/cronLog.log 2>&1" >> currentCron
crontab currentCron
sudo rm currentCron

echo "------Done------"
